package fr.cci.ProjetJava.SimVille.Projet.controller;

import fr.cci.ProjetJava.SimVille.Projet.model.Terrain;
import fr.cci.ProjetJava.SimVille.Projet.model.Ville;
import fr.cci.ProjetJava.SimVille.Projet.model.repository.TerrainRepository;
import fr.cci.ProjetJava.SimVille.Projet.model.repository.VilleRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/terrain")
public class TerrainController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private TerrainRepository terrainRepository;

    @PostMapping(path = "/add") // Map ONLY GET Requests
    public @ResponseBody
    String addNewTerrain(@RequestParam String terrainImgUrl, @RequestParam Integer terrainType,
                         @RequestParam String terrainNomShort, @RequestParam String terrainNom)
    {
        Terrain t = new Terrain();
        t.setTerrainImgUrl(terrainImgUrl);
        t.setTerrainType(terrainType);
        t.setTerrainNomShort(terrainNomShort);
        terrainRepository.save(t);
        return "Saved";
    }

    @GetMapping(path = "/all")
    public @ResponseBody
    Iterable<Terrain> getAllUsers() {
        // This returns a JSON or XML with the users
        return terrainRepository.findAll();
    }
}
