package fr.cci.ProjetJava.SimVille.Projet.controller;

import fr.cci.ProjetJava.SimVille.Projet.model.Terrain;
import fr.cci.ProjetJava.SimVille.Projet.model.TuileCarte;
import fr.cci.ProjetJava.SimVille.Projet.model.Ville;
import fr.cci.ProjetJava.SimVille.Projet.model.repository.TerrainRepository;
import fr.cci.ProjetJava.SimVille.Projet.model.repository.TuileCarteRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/tuilecarte")
public class TuileCarteController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private TuileCarteRepository tuileCarteRepository;

    @PostMapping(path = "/add") // Map ONLY GET Requests
    public @ResponseBody
    String addNewTuileCarte(@RequestParam Integer tuileCarteposition,
                            @RequestParam Ville ville, @RequestParam Terrain terrain)
    {
        TuileCarte t = new TuileCarte();
        t.setTuileCarteposition(tuileCarteposition);
        t.setVille(ville);
        t.setTerrain(terrain);
        tuileCarteRepository.save(t);
        return "Saved";
    }

    @GetMapping(path = "/all")
    public @ResponseBody
    Iterable<TuileCarte> getAllUsers() {
        // This returns a JSON or XML with the users
        return  tuileCarteRepository.findAll();
    }
}
